version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-customers-api
    tty: true
    restart: always
    volumes: 
      - .:/app
    working_dir: '/app'
    expose: 
      - "4000"
    networks:
      services:
        ipv4_address: 10.10.0.22

  postgres:
    image: postgres:11
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=node-api-db
      - POSTGRES_USER=adm
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./data/volumes/postgres:/var/lib/postgresql/data
      - ./data/dump:/var/lib/postgresql/dump
    networks:
      services:
        ipv4_address: 10.10.0.32

networks:
  services:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/20
          
          
